### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by mkuratczyk** [krujos/willitconnect#3]
Hi Joshua,

I get the following error:
$ ./gradlew assemble
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

I believe it is due to "*.jar" in .gitignore (gradle wrapper doesn't make it to the repo).

Thanks,

**Comment by krujos** [comment]
Mind giving it another shot, I believe it's fixed but would like verification!

Thanks!

**Comment by mkuratczyk** [comment]
Thanks Joshua. Builds, deploys and works great.
