### ISSUE TITLE
Result is different if external url is qualified with http or https vs not

### ISSUE THREAD

**Issue by cas0016** [krujos/willitconnect#73]
When the external url has http or https, wic shows it as unable to connect.

However when it does not contain http or https, it says success.

**Comment by gambtho** [comment]
Which version are you using?   I'm not able to recreate this with the latest
<img width="1272" alt="screen shot 2016-08-03 at 10 03 52 am" src="https://cloud.githubusercontent.com/assets/14336279/17374471/9d8fe658-5961-11e6-8ac7-711366e520d3.png">

**Comment by krujos** [comment]
I think in the slack screen shot he was using a proxy. The results are backwards from how I'd have expected it to work

**Comment by cas0016** [comment]
![pasted image at 2016_08_02 16_26](https://cloud.githubusercontent.com/assets/17220897/17376022/a80bba9c-5981-11e6-9dce-57b35bf7acd2.png)
<img width="1680" alt="screen shot 2016-08-02 at 4 23 25 pm" src="https://cloud.githubusercontent.com/assets/17220897/17376024/aa329d2c-5981-11e6-8ef8-bc178c761444.png">

**Comment by gambtho** [comment]
got it -- old version.  Will push a new one out there as soon as I can get the vpn to cooperate
