### ISSUE TITLE
1.0.5 has issue with proxy

### ISSUE THREAD

**Issue by avasseur-pivotal** [krujos/willitconnect#82]
The check button does not apply due to a javascript error
   if (this.state.isChecked) {
	                proxyHost = this.refs.proxyHost.getValue();
	                proxyPort = this.refs.proxyPort.getValue();
	            }
tested on Firefox and Chrome

TypeError: this.refs.proxyHost.getValue is not a function
proxyHost = this.refs.proxyHost.getValue();

**Comment by gambtho** [comment]
fixed with 1.0.7 -- thanks for the issue info
